# Generated by Django 5.2.9 on 2025-12-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_custom_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='simpleuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Simple User'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag'},
        ),
    ]
