# Generated by Django 5.2.9 on 2025-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_post_options_alter_simpleuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
