# Generated by Django 5.2.9 on 2025-12-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_groups_user_groups'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.CharField(choices=[('G', 10), ('S', 5), ('B', 2)], default='B', max_length=1),
        ),
    ]
