# Generated by Django 5.2.9 on 2025-12-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_alter_patient_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='name',
            field=models.CharField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(),
        ),
    ]
