# Generated by Django 5.2.9 on 2025-12-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_alter_doctor_name_alter_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='contact_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='name',
            field=models.CharField(),
        ),
    ]
