# Generated by Django 5.2.9 on 2025-12-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_alter_doctor_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpatients', to='queries.patient'),
        ),
    ]
